job ('First-Maven-Project-Via-DSL') {
	
	description ("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
	scm {
		git("https://github.com/ashwin-p-m/jenkins-test.git", 'master')
	}
	triggers {
		scm('* * * * *')
	}
	steps {
		maven('clean package', 'UMUtility/Server/usermigrationutility/pom.xml')
	}
	publishers {
		archiveArtifacts '**/*.jar'
	}
	
}